default_language_version:
  python: python3
exclude: |
  (?x)
      # others
      ^(.mypy_cache|.pytest_cache|.venv|.venv_dev|.tox|logs)/
repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        language_version: python3.8
        additional_dependencies:
          - flake8-typing-imports==1.14.0
          - flake8-bugbear == 23.1.17
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [ --py38-plus ]
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        args: [ --safe, --quiet, --line-length=120 ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: fix-encoding-pragma
        args: [ --remove ]
      - id: check-yaml
      - id: debug-statements
        language_version: python3
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.8.0
    hooks:
      - id: mypy
        args: [ ]
        additional_dependencies:
          - iniconfig>=1.1.0
          - py>=1.8.2
          - attrs>=19.2.0
          - packaging
          - tomli
          # mypy types
          - types-atomicwrites
          - types-pkg_resources
